#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
uav_mission_2.py
Auto-generated by SkyOps UAV-VLA System
Task  : 2
Time  : 2026-05-25 03:28:25
Points: 12 waypoints @ 20.0 m AGL
"""

import rclpy
from rclpy.node import Node
from geometry_msgs.msg import PoseStamped
from mavros_msgs.srv import CommandBool, SetMode
from mavros_msgs.msg import State
import time


# ──────────────────────────── 任务参数 ────────────────────────────────────────
WAYPOINTS_GPS = [
    (43.02537063, -85.78686182),  # WP1
    (43.02458185, -85.78668122),  # WP2
    (43.02274138, -85.78668122),  # WP3
    (43.02166271, -85.78648160),  # WP4
    (43.02382004, -85.78486566),  # WP5
    (43.02154810, -85.78478011),  # WP6
    (43.02523579, -85.78475159),  # WP7
    (43.02260654, -85.78439988),  # WP8
    (43.02168294, -85.78399114),  # WP9
    (43.02179754, -85.78249877),  # WP10
    (43.02328071, -85.78221361),  # WP11
    (43.02146046, -85.78221361),  # WP12
]  # list of (latitude, longitude)

TARGET_ALTITUDE  = 20.0   # metres (AGL)
CRUISE_SPEED_MPS = 5.0       # m/s (仅参考，实际由 PX4 MPC 控制器管理)
HOLD_TIME_SEC    = 2       # 到达每个航点后的悬停时间(s)


# ──────────────────────────── ROS2 节点 ───────────────────────────────────────
class UAVMissionNode(Node):
    """
    基于 mavros 的无人机任务控制节点。
    通信接口：
      - 订阅  /mavros/state          : 获取飞控连接状态
      - 发布  /mavros/setpoint_position/local : 发送位置设定点
      - 服务  /mavros/cmd/arming      : ARM / DISARM
      - 服务  /mavros/set_mode        : 切换 PX4 飞行模式
    """

    def __init__(self):
        super().__init__('uav_mission_node')
        self.current_state = State()

        # ── 订阅飞控状态 ──
        self.state_sub = self.create_subscription(
            State, '/mavros/state', self._state_cb, 10)

        # ── 位置设定点发布器 ──
        self.local_pos_pub = self.create_publisher(
            PoseStamped, '/mavros/setpoint_position/local', 10)

        # ── ARM / DISARM 服务 ──
        self.arming_client = self.create_client(CommandBool, '/mavros/cmd/arming')
        while not self.arming_client.wait_for_service(timeout_sec=1.0):
            self.get_logger().info('等待 arming 服务...')

        # ── 模式切换服务 ──
        self.set_mode_client = self.create_client(SetMode, '/mavros/set_mode')
        while not self.set_mode_client.wait_for_service(timeout_sec=1.0):
            self.get_logger().info('等待 set_mode 服务...')

    # ── 回调 ──────────────────────────────────────────────────────────────────
    def _state_cb(self, msg: State):
        self.current_state = msg

    # ── 工具函数 ─────────────────────────────────────────────────────────────
    def _set_arm(self, arm: bool):
        req = CommandBool.Request()
        req.value = arm
        future = self.arming_client.call_async(req)
        rclpy.spin_until_future_complete(self, future)
        label = "ARM" if arm else "DISARM"
        if future.result() and future.result().success:
            self.get_logger().info(f'[✓] {label} 成功')
        else:
            self.get_logger().warn(f'[!] {label} 失败')

    def _set_mode(self, mode: str):
        req = SetMode.Request()
        req.custom_mode = mode
        future = self.set_mode_client.call_async(req)
        rclpy.spin_until_future_complete(self, future)
        if future.result() and future.result().mode_sent:
            self.get_logger().info(f'[✓] 模式切换 -> {mode}')
        else:
            self.get_logger().warn(f'[!] 模式切换失败: {mode}')

    def _publish_setpoint(self, x: float, y: float, z: float):
        """发布 ENU 坐标系下的本地位置设定点（GPS 转换后使用）"""
        sp = PoseStamped()
        sp.header.stamp = self.get_clock().now().to_msg()
        sp.header.frame_id = 'map'
        sp.pose.position.x = x
        sp.pose.position.y = y
        sp.pose.position.z = z
        self.local_pos_pub.publish(sp)

    # ── 主任务序列 ────────────────────────────────────────────────────────────
    def execute_mission(self):
        self.get_logger().info('═══ 任务开始 ═══')

        # 1. 等待 FCU 连接
        self.get_logger().info('[1/5] 等待飞控连接...')
        timeout = 10.0
        t0 = time.time()
        while not self.current_state.connected:
            rclpy.spin_once(self, timeout_sec=0.1)
            if time.time() - t0 > timeout:
                self.get_logger().error('飞控连接超时，任务终止')
                return

        # 2. 预发送设定点（OFFBOARD 模式需要预先接收到设定点流）
        self.get_logger().info('[2/5] 预发送设定点...')
        for _ in range(100):
            self._publish_setpoint(0.0, 0.0, TARGET_ALTITUDE)
            time.sleep(0.05)

        # 3. 切换 OFFBOARD 模式并 ARM
        self.get_logger().info('[3/5] 切换 OFFBOARD 模式并解锁...')
        self._set_mode('OFFBOARD')
        time.sleep(0.5)
        self._set_arm(True)
        time.sleep(1.0)

        # 4. 起飞 —— 在原地升至目标高度
        self.get_logger().info(f'[4/5] 起飞至 {TARGET_ALTITUDE:.1f} m ...')
        for _ in range(50):
            self._publish_setpoint(0.0, 0.0, TARGET_ALTITUDE)
            time.sleep(0.1)
        time.sleep(3.0)

        # 5. 按序导航各 GPS 航点
        # ⚠️  注意：此处使用的是 GPS 坐标列表，实际部署时需通过
        #    mavros/global_position 话题将 GPS 转换为本地 ENU 坐标。
        #    在仿真（Gazebo + SITL）中，可直接使用 GPS 坐标配合
        #    mavros 的 global_setpoint 话题。
        self.get_logger().info(f'[5/5] 开始巡航 {len(WAYPOINTS_GPS)} 个航点...')
        for idx, (lat, lon) in enumerate(WAYPOINTS_GPS):
            self.get_logger().info(
                f'  → 航点 {idx + 1}/{len(WAYPOINTS_GPS)}: '
                f'lat={lat:.6f}, lon={lon:.6f}'
            )
            # 此处以 lat/lon 作为 x/y 占位（仿真中需替换为本地坐标转换）
            for _ in range(30):
                self._publish_setpoint(float(lat), float(lon), TARGET_ALTITUDE)
                time.sleep(0.1)
            self.get_logger().info(f'  ⏸  悬停 {HOLD_TIME_SEC}s ...')
            time.sleep(HOLD_TIME_SEC)

        # 6. 自动返航 RTL
        self.get_logger().info('[RTL] 发送自动返航指令...')
        self._set_mode('AUTO.RTL')
        time.sleep(2.0)

        # 7. DISARM（可选：RTL 降落后自动 DISARM）
        self.get_logger().info('[DISARM] 上锁...')
        self._set_arm(False)

        self.get_logger().info('═══ 任务完成 ═══')


# ──────────────────────────── 入口 ────────────────────────────────────────────
def main(args=None):
    rclpy.init(args=args)
    node = UAVMissionNode()
    node.execute_mission()
    node.destroy_node()
    rclpy.shutdown()


if __name__ == '__main__':
    main()
