"""
flight_exporter.py
==================
双路工业接口输出引擎（Template Injection 策略）
  - 第一路：ROS2 rclpy + mavros 控制节点脚本 (.py)
  - 第二路：QGroundControl 标准飞行计划文件 (.plan)

使用方式（供 app.py / service_layer 调用）：
    from flight_exporter import generate_ros2_script, generate_qgc_plan
    ros2_code : str  = generate_ros2_script(waypoints, task_name, altitude=20.0)
    plan_json  : str  = generate_qgc_plan(waypoints, task_name, altitude=20.0)
"""

import json
import os
from datetime import datetime
from typing import List, Tuple

# ── 默认参数 ─────────────────────────────────────────────────────────────────
DEFAULT_ALTITUDE  = 20.0   # 飞行高度(m)，AGL
DEFAULT_SPEED     = 5.0    # 飞行速度(m/s)
DEFAULT_HOLD_TIME = 2      # 每个航点悬停(s)
EXPORT_DIR        = "exported_plans"   # 导出文件目录


# ═══════════════════════════════════════════════════════════════════════════════
#  路 一：ROS 2 rclpy + mavros 控制节点脚本
# ═══════════════════════════════════════════════════════════════════════════════

_ROS2_TEMPLATE = '''\
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
{script_name}
Auto-generated by SkyOps UAV-VLA System
Task  : {task_name}
Time  : {gen_time}
Points: {num_waypoints} waypoints @ {altitude:.1f} m AGL
"""

import rclpy
from rclpy.node import Node
from geometry_msgs.msg import PoseStamped
from mavros_msgs.srv import CommandBool, SetMode
from mavros_msgs.msg import State
import time


# ──────────────────────────── 任务参数 ────────────────────────────────────────
WAYPOINTS_GPS = [
{waypoints_block}
]  # list of (latitude, longitude)

TARGET_ALTITUDE  = {altitude:.1f}   # metres (AGL)
CRUISE_SPEED_MPS = {speed:.1f}       # m/s (仅参考，实际由 PX4 MPC 控制器管理)
HOLD_TIME_SEC    = {hold_time}       # 到达每个航点后的悬停时间(s)


# ──────────────────────────── ROS2 节点 ───────────────────────────────────────
class UAVMissionNode(Node):
    """
    基于 mavros 的无人机任务控制节点。
    通信接口：
      - 订阅  /mavros/state          : 获取飞控连接状态
      - 发布  /mavros/setpoint_position/local : 发送位置设定点
      - 服务  /mavros/cmd/arming      : ARM / DISARM
      - 服务  /mavros/set_mode        : 切换 PX4 飞行模式
    """

    def __init__(self):
        super().__init__('uav_mission_node')
        self.current_state = State()

        # ── 订阅飞控状态 ──
        self.state_sub = self.create_subscription(
            State, '/mavros/state', self._state_cb, 10)

        # ── 位置设定点发布器 ──
        self.local_pos_pub = self.create_publisher(
            PoseStamped, '/mavros/setpoint_position/local', 10)

        # ── ARM / DISARM 服务 ──
        self.arming_client = self.create_client(CommandBool, '/mavros/cmd/arming')
        while not self.arming_client.wait_for_service(timeout_sec=1.0):
            self.get_logger().info('等待 arming 服务...')

        # ── 模式切换服务 ──
        self.set_mode_client = self.create_client(SetMode, '/mavros/set_mode')
        while not self.set_mode_client.wait_for_service(timeout_sec=1.0):
            self.get_logger().info('等待 set_mode 服务...')

    # ── 回调 ──────────────────────────────────────────────────────────────────
    def _state_cb(self, msg: State):
        self.current_state = msg

    # ── 工具函数 ─────────────────────────────────────────────────────────────
    def _set_arm(self, arm: bool):
        req = CommandBool.Request()
        req.value = arm
        future = self.arming_client.call_async(req)
        rclpy.spin_until_future_complete(self, future)
        label = "ARM" if arm else "DISARM"
        if future.result() and future.result().success:
            self.get_logger().info(f'[✓] {{label}} 成功')
        else:
            self.get_logger().warn(f'[!] {{label}} 失败')

    def _set_mode(self, mode: str):
        req = SetMode.Request()
        req.custom_mode = mode
        future = self.set_mode_client.call_async(req)
        rclpy.spin_until_future_complete(self, future)
        if future.result() and future.result().mode_sent:
            self.get_logger().info(f'[✓] 模式切换 -> {{mode}}')
        else:
            self.get_logger().warn(f'[!] 模式切换失败: {{mode}}')

    def _publish_setpoint(self, x: float, y: float, z: float):
        """发布 ENU 坐标系下的本地位置设定点（GPS 转换后使用）"""
        sp = PoseStamped()
        sp.header.stamp = self.get_clock().now().to_msg()
        sp.header.frame_id = 'map'
        sp.pose.position.x = x
        sp.pose.position.y = y
        sp.pose.position.z = z
        self.local_pos_pub.publish(sp)

    # ── 主任务序列 ────────────────────────────────────────────────────────────
    def execute_mission(self):
        self.get_logger().info('═══ 任务开始 ═══')

        # 1. 等待 FCU 连接
        self.get_logger().info('[1/5] 等待飞控连接...')
        timeout = 10.0
        t0 = time.time()
        while not self.current_state.connected:
            rclpy.spin_once(self, timeout_sec=0.1)
            if time.time() - t0 > timeout:
                self.get_logger().error('飞控连接超时，任务终止')
                return

        # 2. 预发送设定点（OFFBOARD 模式需要预先接收到设定点流）
        self.get_logger().info('[2/5] 预发送设定点...')
        for _ in range(100):
            self._publish_setpoint(0.0, 0.0, TARGET_ALTITUDE)
            time.sleep(0.05)

        # 3. 切换 OFFBOARD 模式并 ARM
        self.get_logger().info('[3/5] 切换 OFFBOARD 模式并解锁...')
        self._set_mode('OFFBOARD')
        time.sleep(0.5)
        self._set_arm(True)
        time.sleep(1.0)

        # 4. 起飞 —— 在原地升至目标高度
        self.get_logger().info(f'[4/5] 起飞至 {{TARGET_ALTITUDE:.1f}} m ...')
        for _ in range(50):
            self._publish_setpoint(0.0, 0.0, TARGET_ALTITUDE)
            time.sleep(0.1)
        time.sleep(3.0)

        # 5. 按序导航各 GPS 航点
        # ⚠️  注意：此处使用的是 GPS 坐标列表，实际部署时需通过
        #    mavros/global_position 话题将 GPS 转换为本地 ENU 坐标。
        #    在仿真（Gazebo + SITL）中，可直接使用 GPS 坐标配合
        #    mavros 的 global_setpoint 话题。
        self.get_logger().info(f'[5/5] 开始巡航 {{len(WAYPOINTS_GPS)}} 个航点...')
        for idx, (lat, lon) in enumerate(WAYPOINTS_GPS):
            self.get_logger().info(
                f'  → 航点 {{idx + 1}}/{{len(WAYPOINTS_GPS)}}: '
                f'lat={{lat:.6f}}, lon={{lon:.6f}}'
            )
            # 此处以 lat/lon 作为 x/y 占位（仿真中需替换为本地坐标转换）
            for _ in range(30):
                self._publish_setpoint(float(lat), float(lon), TARGET_ALTITUDE)
                time.sleep(0.1)
            self.get_logger().info(f'  ⏸  悬停 {{HOLD_TIME_SEC}}s ...')
            time.sleep(HOLD_TIME_SEC)

        # 6. 自动返航 RTL
        self.get_logger().info('[RTL] 发送自动返航指令...')
        self._set_mode('AUTO.RTL')
        time.sleep(2.0)

        # 7. DISARM（可选：RTL 降落后自动 DISARM）
        self.get_logger().info('[DISARM] 上锁...')
        self._set_arm(False)

        self.get_logger().info('═══ 任务完成 ═══')


# ──────────────────────────── 入口 ────────────────────────────────────────────
def main(args=None):
    rclpy.init(args=args)
    node = UAVMissionNode()
    node.execute_mission()
    node.destroy_node()
    rclpy.shutdown()


if __name__ == '__main__':
    main()
'''


def generate_ros2_script(
    waypoints: List[List[float]],
    task_name: str = "uav_mission",
    altitude: float = DEFAULT_ALTITUDE,
    speed: float = DEFAULT_SPEED,
    hold_time: int = DEFAULT_HOLD_TIME,
) -> str:
    """
    将 GPS 航点列表注入 ROS2 节点模板，返回完整 Python 脚本字符串。

    Parameters
    ----------
    waypoints  : [[lat, lon], ...]
    task_name  : 任务名称（用于注释）
    altitude   : 飞行高度(m)
    speed      : 巡航速度(m/s)
    hold_time  : 每点悬停时间(s)

    Returns
    -------
    str: 完整 ROS2 Python 节点脚本
    """
    safe_name = task_name.replace(" ", "_").replace("/", "_")
    script_name = f"uav_mission_{safe_name}.py"

    wp_lines = "\n".join(
        f"    ({lat:.8f}, {lon:.8f}),  # WP{i+1}"
        for i, (lat, lon) in enumerate(waypoints)
    )

    return _ROS2_TEMPLATE.format(
        script_name=script_name,
        task_name=task_name,
        gen_time=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        num_waypoints=len(waypoints),
        altitude=altitude,
        speed=speed,
        hold_time=hold_time,
        waypoints_block=wp_lines,
    )


# ═══════════════════════════════════════════════════════════════════════════════
#  路 二：QGroundControl .plan 标准文件
# ═══════════════════════════════════════════════════════════════════════════════

def generate_qgc_plan(
    waypoints: List[List[float]],
    task_name: str = "uav_mission",
    altitude: float = DEFAULT_ALTITUDE,
    speed: float = DEFAULT_SPEED,
) -> str:
    """
    将 GPS 航点序列序列化为 QGroundControl 标准 .plan JSON 文件字符串。

    协议规范：
      - fileType       : "Plan"
      - firmwareType   : 12  (PX4)
      - vehicleType    : 2   (Quadrotor)
      - MAV_CMD_NAV_WAYPOINT (16): 普通航点
      - MAV_CMD_NAV_TAKEOFF  (22): 起飞
      - MAV_CMD_NAV_RETURN_TO_LAUNCH (20): RTL

    Parameters
    ----------
    waypoints : [[lat, lon], ...]
    task_name : 任务名称（写入 groundStation 字段）
    altitude  : 所有航点的统一飞行高度(m)
    speed     : 巡航速度(m/s)

    Returns
    -------
    str: JSON 字符串，直接写成 .plan 文件即可由 QGC 导入
    """
    if not waypoints:
        raise ValueError("航点列表不能为空")

    home_lat, home_lon = waypoints[0]
    items = []
    seq = 1  # QGC item 序号从 1 开始

    # ── 1. 起飞指令 MAV_CMD_NAV_TAKEOFF (22) ──────────────────────────────────
    items.append({
        "autoContinue": True,
        "command": 22,          # MAV_CMD_NAV_TAKEOFF
        "doJumpId": seq,
        "frame": 3,             # MAV_FRAME_GLOBAL_RELATIVE_ALT
        "params": [
            15.0,   # param1: 最小倾斜角(°)，固定翼用；多旋翼忽略
            0.0,    # param2: 空
            0.0,    # param3: 空
            float("nan"),  # param4: 偏航角(NaN=保持当前)
            home_lat,
            home_lon,
            altitude        # 起飞高度
        ],
        "type": "SimpleItem"
    })
    seq += 1

    # ── 2. 设置巡航速度 MAV_CMD_DO_CHANGE_SPEED (178) ─────────────────────────
    items.append({
        "autoContinue": True,
        "command": 178,         # MAV_CMD_DO_CHANGE_SPEED
        "doJumpId": seq,
        "frame": 2,             # MAV_FRAME_MISSION
        "params": [
            1.0,    # 速度类型：1=地速
            speed,  # 目标速度(m/s)
            -1.0,   # 油门(-1=不改变)
            0.0, 0.0, 0.0, 0.0
        ],
        "type": "SimpleItem"
    })
    seq += 1

    # ── 3. 逐一添加巡航航点 MAV_CMD_NAV_WAYPOINT (16) ────────────────────────
    for i, (lat, lon) in enumerate(waypoints):
        items.append({
            "autoContinue": True,
            "command": 16,      # MAV_CMD_NAV_WAYPOINT
            "doJumpId": seq,
            "frame": 3,         # MAV_FRAME_GLOBAL_RELATIVE_ALT
            "params": [
                0.0,    # param1: 悬停时间(s)
                0.0,    # param2: 接受半径(m)，0=默认
                0.0,    # param3: 穿越半径(m)
                float("nan"),  # param4: 偏航角
                lat,
                lon,
                altitude
            ],
            "type": "SimpleItem"
        })
        seq += 1

    # ── 4. 自动返航 MAV_CMD_NAV_RETURN_TO_LAUNCH (20) ────────────────────────
    items.append({
        "autoContinue": True,
        "command": 20,          # MAV_CMD_NAV_RETURN_TO_LAUNCH
        "doJumpId": seq,
        "frame": 2,
        "params": [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
        "type": "SimpleItem"
    })

    # ── 组装完整 Plan ──────────────────────────────────────────────────────────
    plan = {
        "fileType": "Plan",
        "version": 1,
        "groundStation": f"SkyOps-UAV-VLA | {task_name}",
        "firmwareType": 12,     # MAV_AUTOPILOT_PX4
        "vehicleType": 2,       # MAV_TYPE_QUADROTOR
        "mission": {
            "cruiseSpeed": speed,
            "firmwareType": 12,
            "globalPlanAltitudeMode": 1,   # 1=relative to home
            "hoverSpeed": 5.0,
            "items": items,
            "plannedHomePosition": [home_lat, home_lon, 0.0],
            "vehicleType": 2,
            "version": 2
        },
        "rallyPoints": {
            "points": [],
            "version": 2
        },
        "geoFence": {
            "circles": [],
            "polygons": [],
            "version": 2
        }
    }

    return json.dumps(plan, ensure_ascii=False, indent=2)


# ═══════════════════════════════════════════════════════════════════════════════
#  文 件 持 久 化 工 具
# ═══════════════════════════════════════════════════════════════════════════════

def save_export_files(
    waypoints: List[List[float]],
    task_id: int,
    task_name: str = "mission",
    altitude: float = DEFAULT_ALTITUDE,
    speed: float = DEFAULT_SPEED,
) -> Tuple[str, str]:
    """
    生成并保存两类导出文件，返回两个文件路径。

    Returns
    -------
    (ros2_path, plan_path)
    """
    os.makedirs(EXPORT_DIR, exist_ok=True)
    safe = task_name.replace(" ", "_").replace("/", "_")
    ts   = datetime.now().strftime("%Y%m%d_%H%M%S")

    ros2_path = os.path.join(EXPORT_DIR, f"task{task_id}_{safe}_{ts}_ros2.py")
    plan_path = os.path.join(EXPORT_DIR, f"task{task_id}_{safe}_{ts}.plan")

    ros2_code = generate_ros2_script(waypoints, task_name, altitude, speed)
    plan_json = generate_qgc_plan(waypoints, task_name, altitude, speed)

    with open(ros2_path, "w", encoding="utf-8") as f:
        f.write(ros2_code)
    with open(plan_path, "w", encoding="utf-8") as f:
        f.write(plan_json)

    return ros2_path, plan_pathpath.join(EXPORT_DIR, f"task{task_id}_{safe}_{ts}.plan")
 
    ros2_code = generate_ros2_script(waypoints, task_name, altitude, speed)
    plan_json = generate_qgc_plan(waypoints, task_name, altitude, speed)
 
    with open(ros2_path, "w", encoding="utf-8") as f:
        f.write(ros2_code)
    with open(plan_path, "w", encoding="utf-8") as f:
        f.write(plan_json)
 
    return ros2_path, plan_path